version: '3.8'

services:
  frontend:
    build: ./frontend
    container_name: bform-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - VITE_BACKEND_URL=http://localhost:5000
      - VITE_TURNSTILE_SITE_KEY=0x4AAAAAAABps-mipfedSSmEU
    depends_on:
      - backend

  backend:
    build: ./backend
    container_name: bform-backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    env_file:
      - .env
    environment:
      - NODE_ENV=development
      - PORT=5000
      - MONGODB_URI=mongodb://mongo:27017/bform
    depends_on:
      - mongo

  mongo:
    image: mongo:7
    container_name: bform-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=bform

volumes:
  mongo_data: